### ISSUE TITLE
Problems setting size

### ISSUE THREAD

**Issue by siideffect** [TBXark/TKSwitcherCollection#3]
Hello, first of all i wanted to say this library looks pretty awesome, so i decided to integrate it in my project. But i have a problem: i am not able to display it properly. I am working programmatically, setting the anchors, but i also tried with frame, making a CGRect. The switch looks always in the wrong proportions. Is there a way to solve this?

**Comment by tbxark** [comment]
Did you use Snpkit or set frame after widget  initialization.

**Comment by siideffect** [comment]
Nope, i just setted constraints using anchors system as i do with all my views.
mySwitcher.leadingAnchor.constraint....

**Comment by tbxark** [comment]
Can you paste your code?Or you use my latest push the code to test again
 [version 1.3.2](https://github.com/TBXark/TKSwitcherCollection/releases/tag/1.3.2).
